server:
  port: 8082

spring:
  application:
    name: flight-service

  profiles: docker

  data:
    mongodb:
      uri: mongodb://mongo:27017/flightdb

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
